Repository SwaveReleaseNote/BackEnd, pull requests merged in 2023-08, with the labels that each got.

#38 따봉 기능 구현
  src/main/java/com/swave/urnr/project/service/ProjectServiceImpl.java
  src/main/java/com/swave/urnr/releasenote/controller/LikedController.java
  src/main/java/com/swave/urnr/releasenote/domain/ReleaseNote.java
  src/main/java/com/swave/urnr/releasenote/repository/LikedCustomRepository.java
  src/main/java/com/swave/urnr/releasenote/repository/LikedCustomRepositoryImpl.java
  src/main/java/com/swave/urnr/releasenote/repository/LikedRepository.java
  src/main/java/com/swave/urnr/releasenote/responsedto/LikedCountResponseDTO.java
  src/main/java/com/swave/urnr/releasenote/responsedto/ReleaseNoteContentResponseDTO.java
  src/main/java/com/swave/urnr/releasenote/service/LikedService.java
  src/main/java/com/swave/urnr/releasenote/service/LikedServiceImpl.java
  src/main/java/com/swave/urnr/releasenote/service/ReleaseNoteServiceImpl.java
  src/main/java/com/swave/urnr/releasenote/service/SeenCheckService.java
  src/main/java/com/swave/urnr/releasenote/service/SeenCheckServiceImpl.java
  src/main/java/com/swave/urnr/util/cqrs/DataSourceConfig.java
  src/main/java/com/swave/urnr/util/cqrs/DataSourceRouter.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/test/java/com/swave/urnr/releasenote/service/LikedServiceImplTest.java
  src/test/java/com/swave/urnr/user/service/UserServiceImplTest.java
Labels: documentation, feature

#44 Opensearch
  build.gradle
  src/main/java/com/swave/urnr/opensearch/config/AbstractOpenSearchConfiguration.java
  src/main/java/com/swave/urnr/opensearch/config/OpenSearchConfig.java
  src/main/java/com/swave/urnr/opensearch/controller/OpenSearchController.java
  src/main/java/com/swave/urnr/opensearch/domain/ProjectOpenSearch.java
  src/main/java/com/swave/urnr/opensearch/domain/UserInProjectOpenSearch.java
  src/main/java/com/swave/urnr/opensearch/domain/UserOpenSearch.java
  src/main/java/com/swave/urnr/opensearch/repository/OpenSearchProjectRepository.java
  src/main/java/com/swave/urnr/opensearch/repository/OpenSearchUserInProjectRepository.java
  src/main/java/com/swave/urnr/opensearch/repository/OpenSearchUserRepository.java
  src/main/java/com/swave/urnr/opensearch/service/OpenSearchIndexService.java
  src/main/java/com/swave/urnr/opensearch/service/OpenSearchIndexServiceImpl.java
  src/main/java/com/swave/urnr/opensearch/service/OpenSearchService.java
  src/main/java/com/swave/urnr/opensearch/service/OpenSearchServiceImpl.java
  src/main/java/com/swave/urnr/project/repository/ProjectRepository.java
  src/main/java/com/swave/urnr/releasenote/requestdto/ReleaseNoteCreateRequestDTO.java
  src/main/java/com/swave/urnr/releasenote/service/CommentServiceImpl.java
  src/main/java/com/swave/urnr/releasenote/service/LikedServiceImpl.java
  src/main/java/com/swave/urnr/releasenote/service/NoteBlockServiceImpl.java
  src/main/java/com/swave/urnr/releasenote/service/ReleaseNoteServiceImpl.java
  src/main/java/com/swave/urnr/releasenote/service/SeenCheckService.java
  src/main/java/com/swave/urnr/releasenote/service/SeenCheckServiceImpl.java
  src/main/java/com/swave/urnr/util/async/AsyncConfig.java
  src/main/resources/application-prod.properties
  src/main/resources/opensearch/project-mapping.json
  src/main/resources/opensearch/project-setting.json
  src/test/java/com/swave/urnr/releasenote/controller/ReleaseNoteControllerTest.java
Labels: enhancement, feature

#50 Feature project redis
  .DS_Store
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/swave/.DS_Store
  src/main/java/com/swave/urnr/.DS_Store
  src/main/java/com/swave/urnr/ReleaseNoteShareSystemApplication.java
  src/main/java/com/swave/urnr/opensearch/controller/OpenSearchController.java
  src/main/java/com/swave/urnr/opensearch/domain/UserOpenSearch.java
  src/main/java/com/swave/urnr/opensearch/service/OpenSearchService.java
  src/main/java/com/swave/urnr/opensearch/service/OpenSearchServiceImpl.java
  src/main/java/com/swave/urnr/project/controller/ProjectController.java
  src/main/java/com/swave/urnr/project/domain/Project.java
  src/main/java/com/swave/urnr/project/responsedto/ProjectContentResponseDTO.java
  src/main/java/com/swave/urnr/project/responsedto/ProjectSearchContentResponseDTO.java
  src/main/java/com/swave/urnr/project/responsedto/ProjectSearchResultListResponseDTO.java
  src/main/java/com/swave/urnr/project/service/ProjectService.java
  src/main/java/com/swave/urnr/project/service/ProjectServiceImpl.java
  src/main/java/com/swave/urnr/redis/RedisConfig.java
  src/main/java/com/swave/urnr/redis/RedisController.java
  src/main/java/com/swave/urnr/redis/RedisLockRepository.java
  src/main/java/com/swave/urnr/redis/RedisService.java
  src/main/java/com/swave/urnr/releasenote/controller/CommentController.java
  src/main/java/com/swave/urnr/releasenote/controller/LikedController.java
  src/main/java/com/swave/urnr/releasenote/controller/NoteBlockController.java
  src/main/java/com/swave/urnr/releasenote/controller/ReleaseNoteController.java
  src/main/java/com/swave/urnr/releasenote/service/ReleaseNoteService.java
  src/main/java/com/swave/urnr/releasenote/service/ReleaseNoteServiceImpl.java
  src/main/java/com/swave/urnr/user/controller/UserController.java
  src/main/java/com/swave/urnr/user/controller/UserInProjectController.java
  src/main/java/com/swave/urnr/user/responsedto/UserMemberInfoResponseDTO.java
  src/main/java/com/swave/urnr/user/service/UserInProjectServiceImpl.java
  src/main/java/com/swave/urnr/user/service/UserServiceImpl.java
  src/main/java/com/swave/urnr/util/swagger/SwaggerConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/test/java/com/swave/urnr/project/service/ProjectServiceTest.java
  src/test/java/com/swave/urnr/releasenote/service/ReleaseNoteServiceImplTest.java
  src/test/java/com/swave/urnr/user/service/UserInProjectServiceImplTest.java
Labels: enhancement
